<?php

$fechaActual = date("Y-m-d");


mysqli_query($conn3, "INSERT INTO  objetivosTerapiaOcupacional
SET 
ID_Usuario = '$usuario_id',
ID_Cliente = '$clienteId',
ID_Historia_Ocupacional = '$historiaClinica1',
fechaCreacion = '$fechaActual',
DC_IntegracionSensorial = '{$_POST['DC_IntegracionSensorial']}',
EIP_IntegracionSensorial = '{$_POST['EIP_IntegracionSensorial']}',
OBJ_IntegracionSensorial = '{$_POST['OBJ_IntegracionSensorial']}',
RES_IntegracionSensorial = '{$_POST['RES_IntegracionSensorial']}',
P_IntegracionSensorial = '{$_POST['P_IntegracionSensorial']}',
DC_PorcesamientoSensorial = '{$_POST['DC_PorcesamientoSensorial']}',
EIP_PorcesamientoSensorial = '{$_POST['EIP_PorcesamientoSensorial']}',
OBJ_PorcesamientoSensorial = '{$_POST['OBJ_PorcesamientoSensorial']}',
RES_PorcesamientoSensorial = '{$_POST['RES_PorcesamientoSensorial']}',
P_PorcesamientoSensorial = '{$_POST['P_PorcesamientoSensorial']}',
DC_DestrezasPerceptuales = '{$_POST['DC_DestrezasPerceptuales']}',
EIP_DestrezasPerceptuales = '{$_POST['EIP_DestrezasPerceptuales']}',
OBJ_DestrezasPerceptuales = '{$_POST['OBJ_DestrezasPerceptuales']}',
RES_DestrezasPerceptuales = '{$_POST['RES_DestrezasPerceptuales']}',
P_DestrezasPerceptuales = '{$_POST['P_DestrezasPerceptuales']}',
DC_ControlPostural = '{$_POST['DC_ControlPostural']}',
EIP_ControlPostural = '{$_POST['EIP_ControlPostural']}',
OBJ_ControlPostural = '{$_POST['OBJ_ControlPostural']}',
RES_ControlPostural = '{$_POST['RES_ControlPostural']}',
P_ControlPostural = '{$_POST['P_ControlPostural']}',
DC_ControlPostural2 = '{$_POST['DC_ControlPostural2']}',
EIP_ControlPostural2 = '{$_POST['EIP_ControlPostural2']}',
OBJ_ControlPostural2 = '{$_POST['OBJ_ControlPostural2']}',
RES_ControlPostural2 = '{$_POST['RES_ControlPostural2']}',
P_ControlPostural2 = '{$_POST['P_ControlPostural2']}',
DC_HabilidadesMotoras = '{$_POST['DC_HabilidadesMotoras']}',
EIP_HabilidadesMotoras = '{$_POST['EIP_HabilidadesMotoras']}',
OBJ_HabilidadesMotoras = '{$_POST['OBJ_HabilidadesMotoras']}',
RES_HabilidadesMotoras = '{$_POST['RES_HabilidadesMotoras']}',
P_HabilidadesMotoras = '{$_POST['P_HabilidadesMotoras']}',
DC_Bipedo = '{$_POST['DC_Bipedo']}',
EIP_Bipedo = '{$_POST['EIP_Bipedo']}',
OBJ_Bipedo = '{$_POST['OBJ_Bipedo']}',
RES_Bipedo = '{$_POST['RES_Bipedo']}',
P_Bipedo = '{$_POST['P_Bipedo']}',
DC_HabilidadesMotorasFinas = '{$_POST['DC_HabilidadesMotorasFinas']}',
EIP_HabilidadesMotorasFinas = '{$_POST['EIP_HabilidadesMotorasFinas']}',
OBJ_HabilidadesMotorasFinas = '{$_POST['OBJ_HabilidadesMotorasFinas']}',
RES_HabilidadesMotorasFinas = '{$_POST['RES_HabilidadesMotorasFinas']}',
P_HabilidadesMotorasFinas = '{$_POST['P_HabilidadesMotorasFinas']}',
DC_LateralidadCruce = '{$_POST['DC_LateralidadCruce']}',
EIP_LateralidadCruce = '{$_POST['EIP_LateralidadCruce']}',
OBJ_LateralidadCruce = '{$_POST['OBJ_LateralidadCruce']}',
RES_LateralidadCruce = '{$_POST['RES_LateralidadCruce']}',
P_LateralidadCruce = '{$_POST['P_LateralidadCruce']}',
DC_CoordinacionVisomotriz = '{$_POST['DC_CoordinacionVisomotriz']}',
EIP_CoordinacionVisomotriz = '{$_POST['EIP_CoordinacionVisomotriz']}',
OBJ_CoordinacionVisomotriz = '{$_POST['OBJ_CoordinacionVisomotriz']}',
RES_CoordinacionVisomotriz = '{$_POST['RES_CoordinacionVisomotriz']}',
P_CoordinacionVisomotriz = '{$_POST['P_CoordinacionVisomotriz']}',
DC_IntegracionBilateral = '{$_POST['DC_IntegracionBilateral']}',
EIP_IntegracionBilateral = '{$_POST['EIP_IntegracionBilateral']}',
OBJ_IntegracionBilateral = '{$_POST['OBJ_IntegracionBilateral']}',
RES_IntegracionBilateral = '{$_POST['RES_IntegracionBilateral']}',
P_IntegracionBilateral = '{$_POST['P_IntegracionBilateral']}',
DC_ToleraciaPT = '{$_POST['DC_ToleraciaPT']}',
EIP_ToleraciaPT = '{$_POST['EIP_ToleraciaPT']}',
OBJ_ToleraciaPT = '{$_POST['OBJ_ToleraciaPT']}',
RES_ToleraciaPT = '{$_POST['RES_ToleraciaPT']}',
P_ToleraciaPT = '{$_POST['P_ToleraciaPT']}',
DC_Praxias = '{$_POST['DC_Praxias']}',
EIP_Praxias = '{$_POST['EIP_Praxias']}',
OBJ_Praxias = '{$_POST['OBJ_Praxias']}',
RES_Praxias = '{$_POST['RES_Praxias']}',
P_Praxias = '{$_POST['P_Praxias']}',
DC_ComponenteCognitivo = '{$_POST['DC_ComponenteCognitivo']}',
EIP_ComponenteCognitivo = '{$_POST['EIP_ComponenteCognitivo']}',
OBJ_ComponenteCognitivo = '{$_POST['OBJ_ComponenteCognitivo']}',
RES_ComponenteCognitivo = '{$_POST['RES_ComponenteCognitivo']}',
P_ComponenteCognitivo = '{$_POST['P_ComponenteCognitivo']}',
DC_ComponentePsicosocial = '{$_POST['DC_ComponentePsicosocial']}',
EIP_ComponentePsicosocial = '{$_POST['EIP_ComponentePsicosocial']}',
OBJ_ComponentePsicosocial = '{$_POST['OBJ_ComponentePsicosocial']}',
RES_ComponentePsicosocial = '{$_POST['RES_ComponentePsicosocial']}',
P_ComponentePsicosocial = '{$_POST['P_ComponentePsicosocial']}'");


?>